#eureka-client
#端口号
server:
    port: 8082

spring:
    application:
        name: service-order
        
eureka:
    instance:
        hostname: localhost
    client:
        service-url:
            #置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址，默认是http://localhost:8761/eureka；多个地址可用，分隔
            default-zone: http://localhost:8761/eureka/
